### ISSUE TITLE
EPU error handling not working in bluesky (not bsui issue)

### ISSUE THREAD

**Issue by ambarb** [NSLS-II-CSX/xf23id1_profiles#5]
Investigate IOC or profile to find the fix to issue reported in https://github.com/NSLS-II/Bug-Reports/issues/178

**Comment by mrakitin** [comment]
It's out of scope of today's deployment visit, should be rather addressed in a separate visit with 1-2 DAMA people.

**Comment by ambarb** [comment]
@ambarb to ask CSX and IOS if they have seen this happen.  maybe we close the issue if no one is reported?

**Comment by ambarb** [comment]
Consulting with others, this seems to be a very rare event.  It isn't worth the investigation and time to try to uncover what is wrong, especially if it was a random bit-flip kind of thing or something the accelerator noticed and fixed.
